name: Docker Image CI # Actions名称

on: [push] # 执行时机

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: yarn

      - name: build project
        run: yarn run build
        
      - name: Build the Docker image # 步骤名字
        run: |
          docker login --username=${{ secrets.DOCKER_USERNAME }} registry.cn-hangzhou.aliyuncs.com --password=${{ secrets.DOCKER_PASSWORD }}
          docker build -t action-test:latest 
          docker tag action-test registry.cn-hangzhou.aliyuncs.com/winnieyun/action-test:latest
          docker push registry.cn-hangzhou.aliyuncs.com/winnieyun/action-test # 推送
